//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConceptosMVC.Models {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DEPT {
        public int DEPT_NO { get; set; }

        [Required(ErrorMessage = "Nombre obligatorio")]
        public string DNOMBRE { get; set; }

        [RegularExpression("^[A-Z](3)$", ErrorMessage = "Debes introducir el nombre correctamente")]
        public string LOC { get; set; }
    }
}
